# Generated by Django 5.1.2 on 2024-10-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
